import Link from 'next/link';
import Image from 'next/image';

/**
 * KAN-184: public-facing affiliate-partners page. Two purposes:
 *
 *   1. Hosts the Sovrn Commerce publisher verification link (the affiliate
 *      network's crawler reaches this page from the homepage footer to
 *      verify Lyra owns checklyra.com).
 *
 *   2. Provides plain-English affiliate disclosure — a small precursor to
 *      the full FTC/UK CMA disclosure UX in KAN-192. Even before the
 *      recommender engine is monetised, having the disclosure live keeps us
 *      ahead of compliance.
 *
 * If you're updating this page, also check the home footer link in
 * src/app/page.tsx (the link is `/partners`).
 */

export const metadata = {
  title: 'Affiliate partners — Lyra',
  description:
    'How Lyra works with affiliate partners, our verification links, and what this means for you.',
};

export default function PartnersPage() {
  return (
    <main className="min-h-screen bg-stone-50">
      <nav className="border-b border-stone-200/60">
        <div className="max-w-3xl mx-auto px-6 h-14 flex items-center">
          <Link href="/" className="flex items-center">
            <Image
              src="/lyra-logo.png"
              alt="Lyra"
              width={32}
              height={32}
              className="h-8 w-auto"
              priority
            />
          </Link>
        </div>
      </nav>

      <article className="max-w-3xl mx-auto px-6 py-10 prose prose-stone prose-sm">
        <h1 className="text-2xl font-[family-name:var(--font-serif)] text-[var(--color-ink)]">
          Affiliate partners
        </h1>
        <p className="text-sm text-[var(--color-muted)]">Last updated: 16 May 2026</p>

        <h2>What we do</h2>
        <p>
          Lyra helps you understand the people you care about so it&apos;s easier to choose
          thoughtful gifts and gestures. To keep Lyra sustainable, some of the gift
          suggestions we surface include affiliate links. If you click one and make a
          purchase, Lyra may earn a small commission from the retailer — at no extra cost
          to you.
        </p>

        <h2>How we choose recommendations</h2>
        <p>
          Recommendations are always driven by the recipient&apos;s profile first.
          Whether a particular product pays Lyra a commission is a secondary signal.
          It is not the reason a recommendation appears. We will never compromise on
          what we think is genuinely a good gift in order to chase a commission.
        </p>

        <h2>Who we work with</h2>
        <p>
          We work with affiliate networks rather than negotiating individual deals
          with every brand. This keeps our recommendations broad and our admin
          surface small. Our current partner is:
        </p>

        <ul>
          <li>
            <strong>Sovrn Commerce</strong> &mdash; an aggregator network that
            provides access to a wide range of retailers under a single contract.
            Verification link:{' '}
            <a
              href="https://sovrn.co/sw3qr9t"
              rel="noopener nofollow"
              className="text-[var(--color-sage)]"
            >
              https://sovrn.co/sw3qr9t
            </a>
            .
          </li>
        </ul>

        <p>
          We may add more affiliate partners (for example direct programmes with
          specific large retailers) in the future. When we do, they&apos;ll be
          listed here.
        </p>

        <h2>What data partners receive</h2>
        <p>
          When you click an affiliate link, the partner network receives the URL
          you clicked, an opaque tracking identifier generated by Lyra, and standard
          browser metadata (your referring page, your user agent, your IP address).
          Lyra never shares your account email address, your name, your profile
          content, or the name or contents of any recipient profile with affiliate
          partners.
        </p>

        <p>
          The opaque identifier lets us reconcile our internal click log against
          the partner&apos;s monthly report so we can pay you the correct amount of
          attention to what&apos;s working &mdash; but it does not identify you to
          the partner.
        </p>

        <h2>How to opt out</h2>
        <p>
          You can use Lyra without ever clicking an affiliate link &mdash; just
          ignore the recommendations. We do not place tracking cookies on your
          device when you visit Lyra; affiliate cookies are only set by the retailer
          after you click a link to their site.
        </p>

        <h2>Questions</h2>
        <p>
          Drop us a note at{' '}
          <a href="mailto:hello@checklyra.com" className="text-[var(--color-sage)]">
            hello@checklyra.com
          </a>{' '}
          if anything here is unclear.
        </p>
      </article>
    </main>
  );
}
